name: DB Releaser
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Assets CLI
        run: npm install -g @map3xyz/assets-cli
      - name: Check out code
        uses: actions/checkout@v2
      - name: Release DB
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }} assets-cli release -d .